# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 312ee718e456bf320a1c6e454597c5622f2ec14b79c7375e3217c4a728e04bd13054a04420498ee1002d7732b35290c0d7f278c7502e6f4b946eebaedfefd06d

test:
  secret_key_base: 04a360180c490d4a029a6ab63510b3d2e39a607f1902b5106be96e3bedc09703568dadbdbe40d13b9be87e0440649a6834e1c5da85854f2b298fad324e745461

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
